config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, shallow: true do
    resources :accounts, only: [:new, :create]
    resources :investments, only: [:new, :create]
    resources :wealth_boosts, only: [:index, :create]
  end
  get 'portfolio_inputs' => 'search#portfolio_inputs'
  get 'results' => 'securities#index'
  get 'import' => 'markets#index'
  post 'import' => 'markets#import'
  get 'input_ticker' => 'markets#input_ticker'

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :accounts
    has_many :investments
    has_many :projections
    has_many :wealth_boosts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @projection_retirement = @user.projections
    @fees_sum_retirement = 0
    @projection_retirement.each do |projection|
      @fees_sum_retirement += projection.fees_paid
    end
    
    @projection_now = @user.projections.where("age < ?", @user.age)
    @fees_sum_now = 0
    @projection_now.each do |projection|
      @fees_sum_now += projection.fees_paid
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_account_path(@user)
    else
      render "new"
    end
  end
  
  def update
    binding.pry
  end
  
  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :income, :email, :password, :password_confirmation, :retired, :current_investments, :current_investments_amount, :investments_length, :current_custodian, :portfolio => []
    )
  end
end

app/views/users/new.html.erb
<div class="homepage-image-container">
  <%= image_tag("home_page.jpg", class: "home-page-photo") %>
  <div class="homepage-image-text">
    The average person loses
    more than $155,000 of their wealth
    to investment fees over time.
  </div>
  <div class="homepage-image-more-text">
    Isn't it time you reclaim your wealth?
  </div>
</div>

<%= form_for @user, html: { class: "first-signup-form"} do |f| %>
  How old are you?
  <%= f.text_field :age %>
  What's your income?
  <%= f.text_field :income %>
  Are you retired?
  Yes: <%= f.radio_button :retired, true %>
  No: <%= f.radio_button :retired, false %>
  <br>
  Do you have investments?
  Yes: <%= f.radio_button :current_investments, true %>
  No: <%= f.radio_button :current_investments, false %>
  <br>
  How much have you invested so far?
  <%= f.text_field :current_investments_amount %>
  How long have you been investing? (rough estimate)
  <%= f.text_field :investments_length %>
  Where are your investments currently held?
  <%= f.text_field :current_custodian %>
  <%= f.submit "Continue", class: "button" %>
<% end %>

app/views/users/show.html.erb
<h1>You've already lost</h1>
<h1><%= @fees_sum_now %></h1>
<h1>You will lose by retirement</h1>
<h1><%= @fees_sum_retirement %></h1>

<%= link_to "Wealth Boost", user_wealth_boosts_path(@user), class: "button", method: :post %>